version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: kf-booking-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kf_booking_system
    volumes:
      - mysql-data:/var/lib/mysql
      - ./app/lib/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - booking-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js App
  nextjs:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: kf-booking-nextjs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./app/.env.local
    depends_on:
      - mysql
    networks:
      - booking-network
    restart: unless-stopped

networks:
  booking-network:
    driver: bridge

volumes:
  mysql-data: